### ISSUE TITLE
Try to reproduce bug related with protoc.exe

### ISSUE THREAD

**Issue by eperinan** [frees-io/freestyle-opscenter#16]
After run `sbt run`:

We are getting the next error in Linux.

`Caused by: java.io.IOException: Cannot run program "/home/raulraja/protocjar3064826002797437955/bin/protoc.exe": error=2, No such file or directory`

**Comment by calvellido** [comment]
I am on a Debian based distro and I am not able to reproduce the error. I have `protobuf-compiler 3.1.0` on my system.

**Comment by eperinan** [comment]
Thanks for trying to reproduce this bug @calvellido.

I tried to reproduce with @israelperezglez as well the bug and it works fine as well. Despite he doesn't have install `protoc` in his machine.

Could you confirm that the bug is solved @raulraja ? After the changes related with scalapb to pbdirect, we are not using the protoc binary.

**Comment by raulraja** [comment]
:+1:
