### ISSUE TITLE
Generate .proto file from case class

### ISSUE THREAD

**Issue by eperinan** [frees-io/freestyle-opscenter#23]
We have to use `sbt-freestyle-protogen`to generate the .proto file from case class with anotation `@message`

**Comment by eperinan** [comment]
We are blocked by this issue https://github.com/47deg/sbt-org-policies/issues/655 and https://github.com/frees-io/sbt-freestyle-protogen/issues/12

**Comment by eperinan** [comment]
@suhasgaddam unblocked this issue and I can generate .proto files right now. 

After this, we have another problem that I reported in this issue https://github.com/frees-io/sbt-freestyle-protogen/issues/19

For this reason we continue blocked again

**Comment by juanpedromoreno** [comment]
IMHO You are not blocked at all.

If you want to finish your task you could:

* Get rid of the type alias, you don't need it for a simple `List[Metric]`.
* In my short experience with protocol buffers I've never seen jodatime, in fact, I'm not sure if dates/times are well supported by protobuf (I might be wrong, perhaps you have the possibility to use a special protobuf timestamp or something like that). In summary, you even could change it by a `long` (`int64`).

**Comment by juanpedromoreno** [comment]
More on the datetime: https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto

For `proto3`, in case you are interested.

**Comment by eperinan** [comment]
Thanks for your reply.

Ok I will change the type alia to `List[Metric]` meanwhile.

The another topic, I knew the type `Timestamp` but IMHO we should have the way to transform one  type into another in the proto file.

In my case I want to have the type `Datetime` in the case class but in the proto file the type `long`. For example, Pbdirect supports it with implicits so I think that we could do something like that with another annotation for example.

In this second topic I am blocked unless I change the type in the case class to `long`but I would need confirmation on this because IMHO this is not the expected behaviour.

**Comment by juanpedromoreno** [comment]
You can use custom types, but I guess you would need to implement a protobuf type like the one that I attached below, being sure the rest of the microservices in the ecosystem understand it: 

https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto

In any case, the types you serialize to send out across your microservices not always might match with the types you are managing in your business logic or, even the types stored your database backend.

**Comment by eperinan** [comment]
Totally agree with you, thanks for your explanation buddy.

Finally I defined the field as `Long` to be serializable with proto and I created two implicits to convert the type `Long` to `Datetime` and `Long` to `Datetime`
